name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: aptg Version
      description: What version of aptg are you running? (e.g., v0.1.0)
      placeholder: v0.1.0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How did you encounter the bug?
      placeholder: |
        1. Run `aptg` with config...
        2. Attempt to fetch...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: Expected vs Actual Behavior
      description: What did you expect to happen, and what actually happened?
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant logs from `/var/log/aptg.log` or console output.
      render: shell
